# Generated by Django 5.0.3 on 2024-05-01 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_fooditem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food_item',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
