# Generated by Django 5.0.3 on 2024-05-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_order_food_item_menuitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('STARTERS', 'Starters'), ('MAIN_DISHES', 'Main Dishes'), ('DESSERTS', 'Desserts'), ('DRINKS', 'Drinks')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
